name: Deploy GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate `ads.json`
        run: |
          echo '${{ secrets.A8_BANNER_HTML }}' > ads.json

      - name: Push gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .