name: Deploy GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate `ads.json`
        run: |
          echo '${{ secrets.A8_ADS_JSON }}' > ads.json

      - name: Deploy GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: .
